/* SURVIVE 2050 — EN chrome content map (KO→EN). EVENTS·achievements·persona·sudden-death·receipt. LANG==='en'만 로드. */
window.TX_EN_chrome = {
  /* 돌발 이벤트 */
  "🔥 초대형 아마존 대화재":"🔥 Mega Amazon Wildfire",
  "이번 턴 생태계 타격이 1.85배 가속됩니다.":"This turn, ecosystem damage accelerates 1.85×.",
  "🌊 슈퍼 엘니뇨 동시 발생":"🌊 Super El Niño Strikes",
  "이번 턴 기온 상승 타격이 2.0배 증폭됩니다.":"This turn, warming damage is amplified 2.0×.",
  "🧊 북극 메탄 하이드레이트 대분출":"🧊 Arctic Methane Blowout",
  "이번 턴 모든 악영향이 1.8배 폭주합니다.":"This turn, all harmful effects surge 1.8×.",
  "🌱 글로벌 녹색 보조금 타결":"🌱 Global Green Subsidy Deal",
  "이번 턴 생태 복원 효율이 1.3배 향상됩니다.":"This turn, ecosystem restoration is 1.3× more effective.",
  "🛰️ 위성 조기경보 적중":"🛰️ Satellite Early Warning Hits",
  "이번 턴 기온 타격이 0.65배로 완화됩니다.":"This turn, warming damage is eased to 0.65×.",
  "✊ 청년 기후 총파업":"✊ Youth Climate Strike",
  "이번 턴 생태 복원 효율이 1.35배로 오릅니다.":"This turn, ecosystem restoration rises to 1.35×.",
  "🌡️ 폭염 도미노":"🌡️ Heatwave Domino",
  "임계 근접 — 이번 턴 기온 타격이 2.6배로 폭주합니다.":"Near the brink — this turn, warming damage surges 2.6×.",
  "🕳️ 영구동토 메탄 폭발":"🕳️ Permafrost Methane Burst",
  "언 땅이 뒤집혔다 — 이번 턴 기온 타격이 2.8배로 치솟습니다.":"The frozen earth heaved open — this turn, warming damage spikes 2.8×.",
  "🩸 생태 티핑 경보":"🩸 Ecosystem Tipping Alert",
  "붕괴 직전 — 이번 턴 생태계 타격이 2.2배로 가속됩니다.":"On the edge of collapse — this turn, ecosystem damage accelerates 2.2×.",
  "🌪️ 복합재난 동시타격":"🌪️ Compound Disaster Strike",
  "방심한 사이 — 이번 턴 모든 악영향이 1.8배로 덮칩니다.":"Caught off guard — this turn, all harmful effects hit 1.8×.",
  "❄️ 라니냐 한숨 돌리기":"❄️ La Niña Breather",
  "잠깐의 냉각 — 이번 턴 기온 타격이 0.6배로 줄어듭니다.":"A brief cooling — this turn, warming damage drops to 0.6×.",
  "📈 그린본드 완판":"📈 Green Bonds Sell Out",
  "녹색 채권이 흥행하며 곳간이 두둑해졌다.":"Green bonds were a hit, fattening the treasury.",
  "🏦 긴급 기후기금 배정":"🏦 Emergency Climate Fund",
  "파산 직전, 국제 기후기금이 수혈됐다.":"On the brink of bankruptcy, an international climate fund stepped in.",
  "💸 탄소세 소송 패소":"💸 Carbon Tax Lawsuit Lost",
  "배상 판결로 곳간이 뜯겼다.":"A damages ruling drained the treasury.",
  "📉 그린버블 차익실현":"📉 Green Bubble Sell-Off",
  "과열된 곳간에 차익실현 매물이 쏟아졌다.":"An overheated treasury was hit by a wave of profit-taking.",
  "📺 기후 다큐 신드롬":"📺 Climate Doc Sensation",
  "온 국민이 다큐에 결집했다.":"The whole nation rallied around a documentary.",
  "🗞️ 그린워싱 스캔들":"🗞️ Greenwashing Scandal",
  "위장 환경정책이 폭로됐다.":"A sham eco-policy was exposed.",
  "🚶 기후 난민 대이동":"🚶 Mass Climate Migration",
  "국경에 몰린 난민에 여론이 들끓는다.":"Refugees massing at the border inflame public opinion.",
  "🫧 여론 거품 붕괴":"🫧 Opinion Bubble Bursts",
  "고공 지지율에 방심한 순간 역풍이 불었다.":"A moment of complacency at sky-high approval triggered a backlash.",
  /* 영구 업적 */
  "🕊️ 파리 협정의 전설":"🕊️ Legend of the Paris Accord",
  "평균 기온 상승을 +1.5°C 이하로 완벽히 방어했습니다.":"Held average warming perfectly under +1.5°C.",
  "🌋 끓어버린 지구":"🌋 Boiled Earth",
  "기온 폭주로 인류가 강제 조기 종료되었습니다.":"Runaway heat forced an early end for humanity.",
  "🍂 침묵의 봄":"🍂 Silent Spring",
  "생태계 건강도 0% 도달로 먹이사슬이 전멸했습니다.":"Ecosystem health hit 0% — the food chain was wiped out.",
  "🤖 프랑켄슈타인 테크":"🤖 Frankenstein Tech",
  "위험한 지구공학 카드를 남발하여 생존했습니다.":"Survived by overusing risky geoengineering cards.",
  "🥶 냉혈한 최고사령관":"🥶 Cold-Blooded Commander",
  "생태 지표를 25% 미만으로 버려둔 채 문명만 보존했습니다.":"Preserved civilization while abandoning the ecosystem below 25%.",
  "💚 완벽주의 통제관":"💚 Perfectionist Overseer",
  "10단계 전부에서 「최선(20점)」 보기만 골라냈습니다.":"Picked only the best (20-pt) option in all 10 stages.",
  "🎲 운명의 도박사":"🎲 Gambler of Fate",
  "확률형 도박 보기를 3번 이상 성공시켰습니다.":"Succeeded on 3 or more chance-based gamble options.",
  /* 통치 페르소나(이름) */
  "인류세를 끝낸 선구자":"Pioneer Who Ended the Anthropocene",
  "벼랑 끝의 승부사":"Brinkmanship Gambler",
  "이상주의 통치자":"The Idealist Ruler",
  "냉혹한 실리주의자":"The Ruthless Pragmatist",
  "타협의 생존가":"The Compromising Survivor",
  "줄타기의 균형감각":"The Tightrope Balancer",
  "표류하는 관리자":"The Drifting Administrator",
  /* 조기 붕괴(돌발 사망) 엔딩 */
  "🪦 배드 엔딩: 텅 빈 세계":"🪦 Bad Ending: The Empty World",
  "생태계 건강 지표가 결국 0%를 뚫고 파산했습니다. 벌과 미생물이 사라져 수정이 불가능해졌고 모든 식생이 고사했습니다. 인류는 지하 벙커에서 영양 배양액으로 연명하는 혹독한 디스토피아를 마주합니다.":"Ecosystem health finally broke through 0% and went bankrupt. Bees and microbes vanished, pollination became impossible, and all vegetation withered. Humanity faces a harsh dystopia, scraping by on nutrient broth in underground bunkers.",
  "🪦 배드 엔딩: 끓어버린 지구":"🪦 Bad Ending: The Boiled Earth",
  "평균 기온 상승이 마지노선인 +3.6°C를 넘어서며 시베리아 영구동토층이 완전히 뒤집혔습니다. 기후 제어 능력을 상실한 지구는 방호복 없이 한 걸음도 걸을 수 없는 거대한 용광로가 되었습니다.":"Average warming crossed the +3.6°C red line and Siberia's permafrost flipped wholesale. Having lost all climate control, Earth became a vast furnace where you can't take a step without a hazmat suit.",
  "평균 기온 상승이 마지노선인 +3.0°C를 넘어서며 시베리아 영구동토층이 완전히 뒤집혔습니다. 기후 제어 능력을 상실한 지구는 방호복 없이 한 걸음도 걸을 수 없는 거대한 용광로가 되었습니다.":"Average warming crossed the +3.0°C red line and Siberia's permafrost flipped wholesale. Having lost all climate control, Earth became a vast furnace where you can't take a step without a hazmat suit.",
  /* 영수증 라벨 */
  "통치 결산 영수증 · GOVERNANCE RECEIPT":"GOVERNANCE RECEIPT",
  "통치 스타일":"Governance Style",
  "최애 목표":"Top Goal",
  "🟢 최선의 결단":"🟢 Best Calls",
  "🟡 절충의 선택":"🟡 Compromises",
  "🟠 아쉬운 균형":"🟠 Shaky Balances",
  "🔴 값비싼 선택":"🔴 Costly Choices",
  "🎲 도박 전적":"🎲 Gamble Record",
  "없음":"None",
  "시그니처 정책":"Signature Policy",
  "🌡️ 기온":"🌡️ Temp.", "🌊 해수면":"🌊 Sea Level", "🌱 생태계":"🌱 Ecosystem",
  "최종 등급":"Final Grade", "지속가능성":"Sustainability", "난이도":"Difficulty",
  "고객님의 지구를 이용해 주셔서":"Thank you for using",
  "감사합니다 🌍":"your Earth 🌍",
  "📸 영수증 저장":"📸 Save Receipt", "← 결과 카드":"← Back to Result",
  "🚨 [돌발 속보]":"🚨 [BREAKING]",
  /* 업적/엔딩 상세 모달 */
  "게임 종료 시 평균 기온 상승을 +1.5°C 이하로 막아내세요.":"Keep the average temperature rise at or below +1.5°C by the end of a run.",
  "기온이 폭주해 게임이 강제 종료되는 파멸 엔딩에 도달하세요.":"Reach the doom ending where runaway heat forces an early game over.",
  "생태계 건강도를 0%까지 떨어뜨려 먹이사슬을 붕괴시키세요.":"Let ecosystem health fall to 0% and collapse the food chain.",
  "위험한 지구공학(성층권 살포 등) 보기에 의존해 끝까지 생존하세요.":"Survive to the end by leaning on risky geoengineering options (e.g. stratospheric aerosols).",
  "생태계를 25% 미만으로 방치한 채 문명만 지켜 생존하세요.":"Survive while leaving ecosystem health below 25%, preserving only civilization.",
  "10단계 전부에서 「최선(20점)」 보기만 선택하세요.":"Pick only the best (20-point) option in all 10 stages.",
  "한 판에서 확률형 도박 보기를 3번 이상 성공시키세요.":"Succeed on 3 or more chance-based gamble options in a single run.",
  "봉인되어 있던 「대전환 선언」에 서명해 인류세의 폭주를 멈추고, 지구가 처음으로 스스로 회복의 숨을 들이쉬는 새 시대를 열었습니다.":"You signed the sealed \"Great Transition Declaration,\" halting the Anthropocene's runaway and opening an era where Earth draws its first breath of recovery.",
  "지구공학에 기대지 않고 거의 완벽한 점수와 1.5°C 이하 기온을 동시에 달성한 완전한 탄소중립 낙원입니다.":"A complete carbon-neutral paradise — a near-perfect score and a sub-1.5°C temperature rise achieved without leaning on geoengineering.",
  "탄소는 충분히 줄이지 못했지만 성층권 차단막과 인공 장치를 상시 가동해 연명하는 통제형 인공 에덴입니다.":"A controlled artificial Eden, kept alive by ever-running stratospheric shields and machines despite never cutting carbon enough.",
  "경제 성장을 훼손하지 않으면서 순환경제 100%에 가깝게 도달한, 균형 잡힌 지속가능 미래입니다.":"A balanced, sustainable future that reached near-100% circular economy without sacrificing economic growth.",
  "대부분의 위기에서 지구를 먼저 생각했습니다. 완전한 회복은 아니어도 도시는 안정적으로 점점 더 푸르러집니다.":"You put the planet first in most crises. Not a full recovery, but the city is on a steady track, slowly growing greener.",
  "기온은 어느 정도 막았지만 빙하 해빙으로 해안 대도시가 수몰돼, 인류가 거대한 해상 부유 아크 위에서 문명을 잇습니다.":"Warming was held somewhat in check, but melting ice drowned coastal megacities — humanity carries on atop giant floating arks.",
  "자연 생태계는 사실상 포기하고 모든 녹지를 콘크리트와 기계 숲으로 대체한 채 살아가는 차가운 인공 도시입니다.":"A cold artificial city that all but abandoned nature, replacing every green space with concrete and machine forests.",
  "멸망은 면했지만 매년 슈퍼 태풍과 초대형 가뭄을 일상으로 견뎌야 하는 끈질긴 생존의 궤도입니다.":"You avoided collapse, but entered a grinding survival track where super-typhoons and mega-droughts are an annual norm.",
  "당장의 편리함을 택한 선택이 더 많았습니다. 도시는 형태를 유지하지만 기온과 생태계 모두 위태로운 경계선 위에 있습니다.":"More choices chased short-term convenience. The city still stands, but both temperature and ecosystem teeter on the edge.",
  "국제 공조가 파탄 나고 수억 명의 기후 난민이 발생했습니다. 자원 부국들은 장벽을 높이고 자원 민족주의 전쟁에 돌입합니다.":"International cooperation collapsed and hundreds of millions became climate refugees. Resource-rich nations raise walls and slide into resource-nationalist war.",
  "기온이 임계점을 넘어 폭주하며 인류 문명이 강제로 조기 종료된 파멸의 엔딩입니다.":"Temperature crossed the tipping point and ran away, forcing an early game-over for human civilization.",
  "생태계 건강도가 0%에 도달해 먹이사슬이 전멸하고, 생명이 사라진 텅 빈 세계가 남았습니다.":"Ecosystem health hit 0%, the food chain collapsed entirely, and a hollow world stripped of life remains.",
  "봉인된 「대전환 선언」의 길을 끝까지 밀어붙이고 기온 상승까지 낮게 묶어야 열리는 숨은 최상위 엔딩입니다.":"A hidden top ending — push the sealed \"Great Transition\" path to the very end while keeping the temperature rise low.",
  "위험한 지구공학 없이 거의 완벽에 가까운 점수를 내고 기온 상승을 1.5°C 이하로 묶으세요.":"Score near-perfectly without risky geoengineering, and hold the temperature rise at or below 1.5°C.",
  "최고 수준의 점수를 내되, 위험한 지구공학(성층권 살포) 보기에 한 번이라도 기대 생존하세요.":"Reach a top-tier score, but survive by leaning at least once on risky geoengineering (stratospheric aerosols).",
  "지구공학 없이 최상위권 점수에 도달하되 완벽까지는 닿지 못한 균형형 고득점이면 열립니다.":"Reach a top-tier score without geoengineering, but just short of perfection — a balanced high score.",
  "A등급 컷오프 이상의 높은 점수로 마무리하세요(상위 엔딩 조건엔 못 미치는 안정적 고득점).":"Finish with a high score above the A-grade cutoff — a stable high score that falls short of the top endings.",
  "생존 점수는 확보하되 해수면을 크게 끌어올려(해안 수몰 수준) 마무리하세요.":"Secure a surviving score but finish with sea level pushed dangerously high (coastal-flooding levels).",
  "생존은 했지만 생태계 건강을 25% 미만으로 방치한 채 마무리하세요.":"Survive, but finish with ecosystem health left below 25%.",
  "생존 컷오프는 넘기되 상위·특수 엔딩 조건에는 못 미치는 평범한 생존으로 마무리하세요.":"Pass the survival cutoff but finish with a plain survival that misses the higher or special endings.",
  "낮은 점수(C등급 컷오프 부근)로 간신히 도시 형태만 유지한 채 마무리하세요.":"Finish with a low score (around the C-grade cutoff), barely keeping the city intact.",
  "모든 상위 조건을 놓친 최저 점수로 마무리하면 도달하는 폴백 엔딩입니다.":"The fallback ending — reached by finishing with the lowest score, missing every higher condition.",
  "기온 상승을 통제하지 못하고 임계점(폭주 한계)까지 치솟게 만들면 도달합니다.":"Reached by losing control of the temperature rise and letting it spike to the runaway tipping point.",
  "생태계 건강도를 0%까지 떨어뜨려 먹이사슬을 완전히 붕괴시키면 도달합니다.":"Reached by letting ecosystem health fall all the way to 0%, collapsing the food chain."
};
