/* SURVIVE 2050 EN — early group (auto draft) */
window.TX_EN_early = {
  "도시가 어둠에 잠겼다": "The City Plunged Into Darkness",
  "— 중환자실 간호사: \"인공호흡기가 멈췄어요. 전기가, 지금 당장 필요합니다.\"": "— ICU nurse: \"The ventilators stopped. We need power right now.\"",
  "2050년 한여름, 기록적 폭염으로 전력 수요가 폭발하며 도시 전체가 정전됐다. 모든 선택에는 분명한 이득과 숨은 청구서가 따른다. 어떻게 전력을 복구할 것인가?": "Midsummer 2050: a record heatwave sent power demand soaring, and the entire city went dark. Every option has a clear upside and a hidden bill. How will you restore power?",
  "멈춰둔 석탄 화력발전소를 전부 재가동": "Restart every mothballed coal plant",
  "즉시 복구 · 최악의 탄소": "Instant fix · worst-case carbon",
  "전기는 돌아왔지만 하늘이 잿빛이 됐다.": "The lights came back on, but the sky turned ash-gray.",
  "석탄은 같은 전력량당 가스의 2배, 재생에너지의 수십 배 탄소를 배출하는 가장 더러운 발전원입니다.": "Per unit of electricity, coal emits about twice the carbon of gas and dozens of times that of renewables, making it the dirtiest power source.",
  "2년 전 급히 되살린 석탄발전소의 누적 배출이, 이제서야 청구서가 되어 돌아왔다.": "The accumulated emissions from the coal plants hastily restarted two years ago have finally come due as a bill.",
  "태양광·풍력 단지 + ESS 분산 공급": "Solar & wind farms + distributed ESS storage",
  "무탄소 · 고비용과 간헐성": "Zero-carbon · high cost and intermittency",
  "깨끗한 전기가 도시를 밝혔지만 막대한 예산과 부지가 들었다.": "Clean electricity lit up the city, but it demanded a massive budget and land.",
  "재생에너지+에너지저장장치(ESS) 조합은 간헐성을 보완해 정전 없는 무탄소 전력망의 핵심으로 꼽힙니다.": "Pairing renewables with energy storage systems (ESS) offsets intermittency, making it a cornerstone of blackout-free, zero-carbon power grids.",
  "전 도시 강제 절전령으로 수요를 줄인다": "Cut demand with citywide mandatory power rationing",
  "무탄소 · 산업·일상 마비": "Zero-carbon · industry and daily life grind to a halt",
  "배출은 막았지만 공장이 멈추고 시민이 불편을 견뎠다.": "Emissions were halted, but factories stopped and citizens endured the inconvenience.",
  "가장 깨끗한 에너지는 「쓰지 않은 에너지」지만, 강제 절전은 경제 활동을 직접 위축시키는 대가가 따릅니다.": "The cleanest energy is the energy never used, but forced rationing comes at the cost of directly shrinking economic activity.",
  "들판이 말라붙었다": "The Fields Dried Up",
  "— 농부 김씨: \"올해도 자루가 텅 비었소… 우물이라도 더 파야지 별수 있겠소.\"": "— Farmer Kim: \"The sacks are empty again this year... Guess we've got no choice but to dig more wells.\"",
  "3년째 가뭄으로 곡물 창고가 바닥을 보인다. 어떤 길도 공짜가 아니다. 시민을 먹일 식량 전략을 정하라.": "Three years of drought have emptied the grain stores. No path here is free. Decide the food strategy to feed the people.",
  "지하수를 무제한으로 퍼올린다": "Pump groundwater without limit",
  "즉효 · 대수층 도박": "Instant relief · gambling with the aquifer",
  "당장은 버텼지만 지하수가 고갈됐다.": "It held the line for now, but the groundwater ran dry.",
  "지하수는 보충에 수백~수천 년이 걸려, 과잉 양수는 사실상 비가역적인 자원 고갈입니다.": "Groundwater takes hundreds to thousands of years to recharge, so overpumping is effectively irreversible resource depletion.",
  "운 좋게 대수층이 버텨주었다. 이번엔.": "Lucky break — the aquifer held. This time.",
  "대수층이 주저앉으며 땅이 꺼지기 시작했다.": "The aquifer collapsed, and the ground began to sink.",
  "가뭄저항 작물 + 옥상 도시농업": "Drought-resistant crops + rooftop urban farming",
  "회복형 · 정착까지 시간 소요": "Resilience-building · takes time to take root",
  "옥상마다 콩과 상추가 자랐지만 수확까지는 시간이 걸렸다.": "Beans and lettuce grew on every rooftop, but the harvest took time to come in.",
  "도시농업은 수송 거리(푸드 마일리지)를 줄여 식량 1kg당 탄소 발자국을 크게 낮춥니다.": "Urban farming cuts transport distance (food miles), sharply lowering the carbon footprint per kilogram of food.",
  "이웃 국가에서 식량을 수입한다": "Import food from neighboring countries",
  "즉시 충당 · 의존도 심화": "Instant supply · deepening dependency",
  "배는 채웠지만 의존도가 높아졌다.": "Bellies were filled, but dependency deepened.",
  "곡물 수입 의존이 높을수록 기후로 인한 국제 작황 충격에 식량 안보가 직격탄을 맞습니다.": "The greater the reliance on grain imports, the harder food security is hit by climate-driven shocks to global harvests.",
  "수도꼭지가 말랐다": "The Taps Ran Dry",
  "식수원 수위가 위험 수준으로 떨어졌다. 빠른 해법은 비싸고, 싼 해법은 불편하다. 도시의 물을 어떻게 아낄까?": "Drinking water reserves have fallen to dangerous levels. Fast solutions are expensive; cheap solutions are inconvenient. How will the city conserve water?",
  "병물을 대량 생산·사재기한다": "Mass-produce and stockpile bottled water",
  "즉시 공급 · 플라스틱 폭증": "Instant supply · plastic surge",
  "물은 샀지만 빈 페트병이 산을 이뤘다.": "Water was secured, but empty bottles piled into mountains.",
  "병입 생수는 수돗물보다 수백 배의 에너지·플라스틱을 쓰며, 생산·수송 과정에서 탄소를 더 배출합니다.": "Bottled water uses hundreds of times more energy and plastic than tap water, emitting more carbon through its production and transport.",
  "빗물 저장 + 노후 수도관 누수 정비": "Rainwater harvesting + aging pipe leak repairs",
  "근본 해법 · 공사 기간 필요": "Root-cause fix · requires construction time",
  "버려지던 빗물이 도시의 식수가 됐지만 정비에 몇 달이 걸렸다.": "Once-wasted rainwater became the city's drinking water, but repairs took months.",
  "전 세계 상수도의 20~30%가 노후관 누수로 사라집니다. 누수 정비는 가장 값싼 수자원 확보책입니다.": "20-30% of the world's piped water is lost to aging-pipe leaks. Leak repair is the cheapest way to secure water resources.",
  "시간제 급수로 사용을 제한한다": "Restrict usage with scheduled water rationing",
  "무비용 · 시민 불편 감수": "No cost · citizens bear the inconvenience",
  "불편했지만 위기를 함께 넘겼다.": "It was inconvenient, but the crisis was weathered together.",
  "수요 관리는 새 댐 건설보다 빠르고 생태 파괴 없이 물 위기를 완충하는 검증된 방법입니다.": "Demand management is a proven way to buffer water crises faster than building new dams, without ecological destruction.",
  "매연에 갇힌 출근길": "Commute Trapped in Smog",
  "출퇴근 차량이 뿜는 매연으로 스모그 경보가 매일 울린다. 편한 길엔 매연이, 옳은 길엔 비용이 따른다. 도시의 이동을 재설계하라.": "Smog alerts blare daily from commuter exhaust. The easy road brings smog; the right road brings cost. Redesign how the city moves.",
  "값싼 경유차에 보조금을 준다": "Subsidize cheap diesel cars",
  "저비용 · 발암 매연 급증": "Low cost · carcinogenic smog surges",
  "도로는 막히고 아이들은 마스크를 썼다.": "Roads jammed up and children wore masks.",
  "경유차 배기가스의 초미세먼지·질소산화물은 WHO가 지정한 1군 발암물질을 포함합니다.": "Diesel exhaust's ultrafine particulates and nitrogen oxides include substances the WHO classifies as Group 1 carcinogens.",
  "자전거·대중교통·보행 중심 도시": "A city built around bikes, transit, and walking",
  "근본 전환 · 막대한 재정": "Fundamental shift · massive financing",
  "차도가 자전거길이 되자 새가 돌아왔지만 막대한 예산이 들었다.": "As roads turned into bike lanes, the birds came back, but it cost a massive budget.",
  "「15분 도시」는 생활권 내 이동을 도보·자전거로 해결해 교통 탄소를 구조적으로 줄입니다.": "The \"15-minute city\" handles local travel by foot and bike, structurally cutting transport carbon.",
  "차량 요일제를 시행한다": "Implement a vehicle no-drive day system",
  "저비용 · 절반의 효과": "Low cost · half the effect",
  "공기가 조금씩 맑아지기 시작했다.": "The air slowly began to clear.",
  "차량 운행 총량 규제는 즉각적인 미세먼지·온실가스 저감 효과가 입증된 정책입니다.": "Capping total vehicle traffic is a policy with proven immediate effects on reducing particulate matter and greenhouse gases.",
  "쓰레기 산이 자란다": "The Trash Mountain Grows",
  "도시 외곽 매립지가 빠르게 차오른다. 묻으면 편하고, 줄이면 반발한다. 늘어나는 쓰레기를 어떻게 다룰까?": "The landfill on the city's edge is filling fast. Burying it is easy; cutting it sparks backlash. How will the growing trash be handled?",
  "매립지를 더 넓게 파낸다": "Dig the landfill wider",
  "즉시 처리 · 메탄과 침출수": "Instant disposal · methane and leachate",
  "침출수가 흘러 토양을 오염시켰다.": "Leachate seeped out and contaminated the soil.",
  "매립지에서 유기물이 썩으며 나오는 메탄은 CO₂보다 수십 배 강한 온실가스입니다.": "Methane released as organic matter rots in landfills is dozens of times more potent a greenhouse gas than CO₂.",
  "묻어두었던 매립지에서 메탄이 새어 나오며, 뒤늦게 하늘을 데우기 시작했다.": "Methane leaking from the buried landfill began belatedly heating the sky.",
  "분리배출·재활용 체계를 정비": "Overhaul waste sorting and recycling systems",
  "자원 순환 · 초기 구축 비용": "Resource circulation · upfront setup cost",
  "쓰레기의 절반이 자원으로 되살아났지만 체계 구축에 투자가 필요했다.": "Half the trash was reborn as resources, but building the system required investment.",
  "재활용 알루미늄은 1차 생산 대비 에너지를 약 95% 절약합니다. 분리배출은 곧 에너지 절약입니다.": "Recycled aluminum saves about 95% of the energy of primary production. Sorting waste is, in effect, saving energy.",
  "쓰레기 종량제를 강화한다": "Strengthen pay-as-you-throw waste fees",
  "발생 감축 · 시민 반발": "Reduces generation · citizen backlash",
  "시민들이 배출량을 스스로 줄였지만 불만도 컸다.": "Citizens cut their own waste output, but discontent ran high.",
  "배출자 부담 원칙(종량제)은 발생량 자체를 줄이는 가장 효과적인 경제적 유인책으로 평가됩니다.": "The polluter-pays principle (volume-based fees) is regarded as the most effective economic incentive for reducing waste generation itself.",
  "견딜 수 없는 폭염": "Unbearable Heatwave",
  "한낮 체감온도가 45℃를 넘겼다. 시원함에는 대가가, 그늘에는 시간이 든다. 온열질환자가 속출하는 도시를 식혀야 한다.": "Midday heat index has topped 45°C. Coolness has a price, and shade takes time to grow. The city, full of heatstroke victims, must be cooled.",
  "모두가 에어컨을 종일 가동한다": "Run air conditioning everywhere, all day",
  "즉시 시원 · 열섬·냉매 악화": "Instant cooling · worsening heat island and refrigerants",
  "실내는 시원했지만 도시는 더 뜨거워졌다.": "Indoors was cool, but the city grew hotter.",
  "에어컨 실외기 열기와 냉매(HFC) 누출은 도시 열섬과 온난화를 동시에 악화시키는 악순환을 만듭니다.": "Heat from AC outdoor units and HFC refrigerant leaks create a vicious cycle that worsens both the urban heat island and global warming.",
  "그늘막·쿨링센터·도시숲을 늘린다": "Expand shade canopies, cooling centers, and urban forests",
  "근본 냉각 · 조성 시간": "Root-cause cooling · takes time to establish",
  "가로수 그늘 아래로 사람들이 모였지만 숲이 자라는 데 시간이 걸렸다.": "People gathered under the shade of street trees, but the forest took time to grow.",
  "도시숲은 증산작용으로 주변 기온을 2~3℃ 낮추는 천연 에어컨 역할을 합니다.": "Urban forests act as natural air conditioners, lowering surrounding temperatures by 2-3°C through transpiration.",
  "폭염 시간대 야외활동 제한": "Restrict outdoor activity during peak heat hours",
  "무비용 · 활동 위축": "No cost · activity shrinks",
  "무리하지 않자 피해가 줄었지만 일상이 멈췄다.": "Not pushing too hard reduced harm, but daily life came to a halt.",
  "폭염은 이미 전 세계에서 가장 많은 인명을 앗아가는 기상재해입니다. 노출 회피가 1차 방어선입니다.": "Heatwaves already claim more lives worldwide than any other weather disaster. Avoiding exposure is the first line of defense.",
  "일회용에 잠긴 일상": "Daily Life Drowning in Disposables",
  "배달과 포장으로 일회용 플라스틱이 넘쳐난다. 편리에는 청구서가, 전환에는 비용이 따른다. 소비 습관을 바꿀 기회다.": "Delivery and packaging have flooded the city with single-use plastic. Convenience has a bill, and change has a cost. This is a chance to shift consumption habits.",
  "값싼 일회용품을 무제한 공급": "Supply unlimited cheap disposables",
  "저비용·편리 · 해양 플라스틱": "Low cost, convenient · ocean plastic",
  "바다거북의 배 속이 플라스틱으로 찼다.": "Sea turtles' stomachs filled with plastic.",
  "매년 약 1,100만 톤의 플라스틱이 바다로 흘러들며, 2050년엔 바다의 플라스틱이 물고기보다 많아질 수 있습니다.": "About 11 million tons of plastic flow into the ocean every year, and by 2050 there could be more plastic in the sea than fish.",
  "다회용기 보증금제를 도입": "Introduce a reusable-container deposit system",
  "폐기물 급감 · 회수 인프라 비용": "Waste plummets · recovery infrastructure cost",
  "한 번 쓰고 버리던 것을 다시 쓰게 됐지만 회수 시스템 구축이 필요했다.": "What was once used and tossed got reused, but building a recovery system was necessary.",
  "보증금 반환제(디포짓)는 다회용기 회수율을 90% 이상으로 끌어올린 사례가 다수 보고됩니다.": "Deposit-refund schemes have been reported to raise reusable container recovery rates above 90% in numerous cases.",
  "일회용품에 사용료를 매긴다": "Charge a fee on disposable items",
  "저비용 · 소비자 저항": "Low cost · consumer resistance",
  "사람들이 텀블러를 챙기기 시작했지만 불만도 있었다.": "People started carrying reusable cups, though some grumbled.",
  "일회용 봉투 유료화만으로도 소비량이 50~80% 급감한 국가 사례가 많습니다.": "In many countries, simply charging for disposable bags has cut consumption by 50-80%.",
  "사라지는 도시의 초록": "The Vanishing Green of the City",
  "개발 압력에 도심 녹지가 줄어든다. 개발엔 이익이, 녹화엔 비용이 든다. 콘크리트 도시에 숨통을 틔워야 한다.": "Development pressure is shrinking the city's green space. Development brings profit; greening brings cost. The concrete city needs room to breathe.",
  "공원을 밀고 주차장을 짓는다": "Bulldoze the park and build a parking lot",
  "개발 이익 · 열섬·흡수원 상실": "Development profit · heat island and lost carbon sink",
  "그늘이 사라지자 도심이 더 달궈졌다.": "As the shade vanished, the downtown grew even hotter.",
  "녹지 1ha는 연간 수 톤의 CO₂를 흡수합니다. 녹지 상실은 탄소 흡수원을 함께 잃는 일입니다.": "One hectare of green space absorbs several tons of CO₂ a year. Losing green space means losing a carbon sink along with it.",
  "옥상정원·가로수 띠를 늘린다": "Expand rooftop gardens and street tree belts",
  "다목적 효과 · 조성 비용": "Multi-purpose benefits · setup cost",
  "건물마다 초록이 번지며 공기가 맑아졌지만 조성에 예산이 들었다.": "Green spread across every building and the air cleared, but it took budget to build.",
  "옥상녹화는 건물 냉방부하를 낮추고 빗물을 머금어 도시 침수까지 완화하는 다목적 인프라입니다.": "Green roofs are multi-purpose infrastructure that lower a building's cooling load and absorb rainwater, even easing urban flooding.",
  "자투리 땅에 작은 화단을 만든다": "Plant small flower beds on leftover land",
  "저비용 · 효과 제한": "Low cost · limited effect",
  "벌과 나비가 다시 도시를 찾았지만 변화는 작았다.": "Bees and butterflies returned to the city, but the change was small.",
  "작은 도시 화단도 꽃가루 매개 곤충의 「징검다리 서식지」가 되어 생물다양성을 잇습니다.": "Even small urban flower beds become \"stepping-stone habitats\" for pollinators, linking up biodiversity.",
  "연안의 물고기가 사라진다": "Coastal Fish Are Disappearing",
  "무분별한 어업으로 연안 어획량이 급감했다. 오늘의 수익과 내일의 바다가 충돌한다. 어민과 바다를 함께 지키려면?": "Reckless fishing has crashed coastal catches. Today's profit collides with tomorrow's ocean. How do you protect both fishers and the sea?",
  "남획을 허용해 수익을 챙긴다": "Allow overfishing to keep the profits",
  "단기 수익 · 어장 도박": "Short-term profit · gambling with the fishery",
  "그물은 찼지만 치어까지 사라졌다.": "The nets filled, but even the juvenile fish vanished.",
  "전 세계 어족자원의 약 3분의 1이 이미 남획 상태로, 회복에는 수년의 휴식이 필요합니다.": "About a third of the world's fish stocks are already overfished, and recovery requires years of rest.",
  "올해는 어군이 운 좋게 돌아왔다.": "Luckily, the fish shoals returned this year.",
  "산란장이 무너지며 어장이 통째로 붕괴했다.": "The spawning grounds collapsed, and the entire fishery crashed with it.",
  "휴어기 + 해양보호구역 지정": "Fishing moratorium + marine protected areas",
  "자원 회복 · 어민 단기 손실": "Resource recovery · short-term losses for fishers",
  "한 철을 쉬자 물고기 떼가 돌아왔지만 어민은 그해를 버텨야 했다.": "Resting for one season brought the fish shoals back, but fishers had to endure that year.",
  "해양보호구역(MPA)은 어획 금지 구역 주변 어장의 어획량까지 늘리는 「넘침 효과」가 확인됩니다.": "Marine Protected Areas (MPAs) have a confirmed \"spillover effect\" that even boosts catches in fisheries surrounding the no-take zones.",
  "어획량 쿼터제를 도입한다": "Introduce a catch quota system",
  "균형 · 회복 더딤": "Balanced · slow recovery",
  "바다와 어민이 균형을 찾았지만 회복은 느렸다.": "The sea and fishers found a balance, but recovery was slow.",
  "과학적 어획 총량(TAC) 관리는 어족 붕괴를 막고 어업을 지속 가능하게 만드는 표준 도구입니다.": "Science-based Total Allowable Catch (TAC) management is the standard tool for preventing stock collapse and making fishing sustainable.",
  "무관심이라는 위기": "The Crisis of Indifference",
  "시민들은 기후 위기를 남의 일로 여긴다. 예산을 아끼면 위기가, 투자하면 효과가 더디다. 행동을 이끌어낼 첫 단추가 필요하다.": "Citizens treat the climate crisis as someone else's problem. Saving the budget deepens the crisis; investing brings slow results. A first step toward action is needed.",
  "캠페인 예산을 전액 삭감한다": "Cut the entire campaign budget",
  "예산 절약 · 위기 심화": "Budget savings · deepening crisis",
  "위기는 조용히 더 깊어졌다.": "The crisis quietly deepened.",
  "기후 위기는 「점진적」이라 체감이 늦어, 인식 부족이 대응 지연의 핵심 원인으로 지목됩니다.": "Because the climate crisis is \"gradual,\" it's slow to register, and lack of awareness is cited as the key reason for delayed response.",
  "학교·시민 참여형 환경교육 확대": "Expand school and community environmental education",
  "행동 변화 · 효과는 장기": "Behavioral change · long-term payoff",
  "아이들이 가정의 변화를 이끌었지만 결실은 천천히 왔다.": "Children led change at home, but results came slowly.",
  "SDG 13의 세부 목표에는 기후 교육·인식 제고가 명시돼 있을 만큼 교육은 핵심 기후 행동입니다.": "Education is so central to climate action that climate education and awareness-raising are explicitly named as a target under SDG 13.",
  "홍보 포스터를 거리에 붙인다": "Put up awareness posters around the city",
  "저비용 · 실천 미약": "Low cost · weak follow-through",
  "관심의 씨앗이 조금씩 퍼졌지만 행동까진 멀었다.": "Seeds of interest slowly spread, but action remained far off.",
  "반복 노출은 행동 변화의 출발점이지만, 정보 제공만으로는 실천까지 이어지지 않는 한계가 있습니다.": "Repeated exposure is a starting point for behavioral change, but information alone has a limit and rarely translates into action.",
  "식량 위기와 배양육 규제": "Food Crisis and Cultured Meat Regulation",
  "가뭄으로 곡물가가 폭등하자 축산 규제 목소리가 커진다. 모든 선택이 누군가의 생계를 건드린다. 미래 식량 정책을 결정하라.": "As drought sends grain prices soaring, calls to regulate livestock grow louder. Every option touches someone's livelihood. Decide the future food policy.",
  "배양육·대체단백질 전면 허가 + 보조금": "Fully approve cultured meat & alt-protein + subsidies",
  "탄소 급감 · 미검증 신기술": "Carbon plummets · unproven new technology",
  "대체 단백질 시장이 활성화되며 축산 탄소 배출이 급감했지만 검증 논란이 남았다.": "The alt-protein market took off and livestock carbon emissions plunged, but safety-verification debates lingered.",
  "대안육·배양육 전환은 전통 축산 대비 토지 사용량을 최대 90% 이상 줄일 수 있습니다.": "Shifting to alt-meat and cultured meat can cut land use by up to 90% or more compared with traditional livestock farming.",
  "전통 축산업 보호 조치만 강화": "Only strengthen protections for traditional livestock farming",
  "농가 안정 · 가축 메탄 폭증": "Farm stability · livestock methane surges",
  "농가는 안도했으나 가축 메탄 배출이 통제 불능에 빠졌다.": "Farms breathed a sigh of relief, but livestock methane emissions spiraled out of control.",
  "가축이 내뿜는 메탄은 20년 기준으로 CO₂보다 온실효과가 80배 이상 강력합니다.": "Methane from livestock has a warming effect over 80 times stronger than CO₂ on a 20-year basis.",
  "식량 배급제 및 유통 통제": "Food rationing and distribution controls",
  "즉시 안정 · 암시장 반발": "Instant stability · black-market backlash",
  "소비는 억제했으나 암시장 형성 등 반발이 일었다.": "Consumption was curbed, but backlash emerged, including the rise of a black market.",
  "기후로 인한 글로벌 식량 생산성 감소는 배급제 이전에 먼저 급격한 식료품 인플레이션으로 나타납니다.": "Climate-driven declines in global food productivity tend to show up first as sharp grocery inflation, even before rationing becomes necessary.",
  "가정용 태양광+가상발전소(VPP)로 분산 대응": "Distributed response with home solar + virtual power plant (VPP)",
  "균형형 · 시민 참여": "Balanced · citizen participation",
  "집집마다 지붕이 작은 발전소가 됐지만, 모으는 데 시간이 들었다.": "Every rooftop became a small power plant, but pooling them took time.",
  "흩어진 지붕 태양광을 묶는 가상발전소(VPP)는 수요 피크를 분산해 정전 위험을 낮춥니다.": "A virtual power plant (VPP) that links scattered rooftop solar spreads out demand peaks, lowering blackout risk.",
  "점적관개·빗물집수로 물을 아껴 짓는다": "Grow crops sparingly with drip irrigation and rainwater harvesting",
  "균형형 · 효율 농법": "Balanced · efficient farming",
  "한 방울도 허투루 쓰지 않자 적은 물로도 작물이 버텼다.": "Wasting not a single drop, the crops held on with little water.",
  "점적관개는 뿌리에 직접 물을 줘 일반 관개보다 물 사용을 최대 60%까지 줄입니다.": "Drip irrigation delivers water directly to the roots, cutting water use by up to 60% compared with conventional irrigation.",
  "중수도(생활하수 재이용)를 도입한다": "Introduce greywater (household wastewater reuse) systems",
  "균형형 · 물 재이용": "Balanced · water reuse",
  "한 번 쓴 물이 화장실·청소용수로 되살아났다.": "Once-used water was reborn as toilet and cleaning water.",
  "중수도 재이용은 깨끗한 식수 수요 자체를 줄이는 검증된 절수 인프라입니다.": "Greywater reuse is proven water-saving infrastructure that reduces the demand for clean drinking water itself.",
  "전기버스·전기택시로 공영 운송 전환": "Convert public transit to electric buses and taxis",
  "균형형 · 운송 전동화": "Balanced · transport electrification",
  "정류장마다 매연 대신 조용한 전기버스가 섰다.": "Quiet electric buses replaced exhaust fumes at every stop.",
  "대중교통 전동화는 도심 미세먼지와 온실가스를 동시에 줄이는 핵심 수단입니다.": "Electrifying public transit is a key way to cut both urban particulate matter and greenhouse gases at once.",
  "음식물쓰레기를 바이오가스로 자원화": "Turn food waste into biogas resources",
  "균형형 · 폐자원 에너지": "Balanced · energy from waste",
  "썩어 메탄을 뿜던 쓰레기가 도시의 연료가 됐다.": "Trash that once rotted and belched methane became the city's fuel.",
  "유기성 폐기물의 혐기소화는 메탄을 포집해 전기·열로 바꾸는 자원순환 기술입니다.": "Anaerobic digestion of organic waste is a circular-economy technology that captures methane and converts it into electricity and heat.",
  "쿨루프(차열 도료)·차열 포장을 확대": "Expand cool roofs (reflective coatings) and heat-reflective pavement",
  "균형형 · 도시 냉각": "Balanced · urban cooling",
  "밝아진 지붕이 햇빛을 되쏘며 도시 온도를 낮췄다.": "Brightened rooftops reflected sunlight back, lowering the city's temperature.",
  "밝은 색 지붕·포장은 햇빛 반사율을 높여 도시 열섬을 식히는 값싼 해법입니다.": "Light-colored roofs and pavement raise solar reflectance, offering a cheap way to cool the urban heat island.",
  "리필 스테이션·표준 다회용기를 보급": "Roll out refill stations and standardized reusable containers",
  "균형형 · 포장 감량": "Balanced · packaging reduction",
  "덜어 쓰는 매장이 늘며 포장재 자체가 줄었다.": "As more stores let customers dispense their own amounts, packaging itself was reduced.",
  "리필·표준 용기 체계는 포장 폐기물을 발생 단계에서 줄이는 가장 근본적 방법입니다.": "Refill and standardized-container systems are the most fundamental way to cut packaging waste at the source.",
  "도시 생태축(그린 네트워크)을 잇는다": "Connect the urban ecological corridor (green network)",
  "균형형 · 녹지 연결": "Balanced · green space connectivity",
  "끊겨 있던 공원들이 초록 띠로 이어졌다.": "Once-disconnected parks were linked by a green belt.",
  "조각난 녹지를 잇는 생태축은 도시 생물다양성과 탄소 흡수의 뼈대가 됩니다.": "Ecological corridors linking fragmented green spaces form the backbone of urban biodiversity and carbon absorption.",
  "혼획 저감 친환경 어구를 보급": "Distribute eco-friendly, bycatch-reducing fishing gear",
  "균형형 · 선택적 어업": "Balanced · selective fishing",
  "잡을 것만 잡는 그물이 치어와 바다거북을 살렸다.": "Nets that caught only the intended fish spared juveniles and sea turtles.",
  "선택성 어구는 목표 외 생물의 혼획을 줄여 어장 자원을 보호합니다.": "Selective fishing gear reduces bycatch of non-target species, protecting fishery resources.",
  "시민 리빙랩·기후 참여예산제를 운영": "Run citizen living labs and climate participatory budgeting",
  "시민이 직접 기획한 실험이 동네를 바꾸기 시작했다.": "Experiments designed by citizens themselves began changing the neighborhood.",
  "시민이 기획·검증에 참여하는 리빙랩은 인식을 실제 행동 변화로 잇습니다.": "Living labs where citizens participate in design and testing turn awareness into real behavioral change.",
  "저메탄 사료·분뇨 바이오가스로 축산 탈탄소": "Decarbonize livestock with low-methane feed and manure biogas",
  "균형형 · 축산 개량": "Balanced · livestock improvement",
  "농가는 유지하되 가축의 메탄 발자국을 줄였다.": "Farms were kept running while livestock's methane footprint was reduced.",
  "사료 첨가제와 분뇨 혐기소화는 전통 축산의 메탄 배출을 실질적으로 낮춥니다.": "Feed additives and anaerobic digestion of manure substantially lower methane emissions from traditional livestock farming."
};
