/* SURVIVE 2050 — EN chrome content map (KO→EN). EVENTS·achievements·persona·sudden-death·receipt. LANG==='en'만 로드. */
window.TX_EN_chrome = {
  /* 돌발 이벤트 */
  "🔥 초대형 아마존 대화재":"🔥 Mega Amazon Wildfire",
  "이번 턴 생태계 타격이 1.85배 가속됩니다.":"This turn, ecosystem damage accelerates 1.85×.",
  "🌊 슈퍼 엘니뇨 동시 발생":"🌊 Super El Niño Strikes",
  "이번 턴 기온 상승 타격이 2.0배 증폭됩니다.":"This turn, warming damage is amplified 2.0×.",
  "🧊 북극 메탄 하이드레이트 대분출":"🧊 Arctic Methane Blowout",
  "이번 턴 모든 악영향이 1.8배 폭주합니다.":"This turn, all harmful effects surge 1.8×.",
  "🌱 글로벌 녹색 보조금 타결":"🌱 Global Green Subsidy Deal",
  "이번 턴 생태 복원 효율이 1.3배 향상됩니다.":"This turn, ecosystem restoration is 1.3× more effective.",
  "🛰️ 위성 조기경보 적중":"🛰️ Satellite Early Warning Hits",
  "이번 턴 기온 타격이 0.65배로 완화됩니다.":"This turn, warming damage is eased to 0.65×.",
  "✊ 청년 기후 총파업":"✊ Youth Climate Strike",
  "이번 턴 생태 복원 효율이 1.35배로 오릅니다.":"This turn, ecosystem restoration rises to 1.35×.",
  "🌡️ 폭염 도미노":"🌡️ Heatwave Domino",
  "임계 근접 — 이번 턴 기온 타격이 2.6배로 폭주합니다.":"Near the brink — this turn, warming damage surges 2.6×.",
  "🕳️ 영구동토 메탄 폭발":"🕳️ Permafrost Methane Burst",
  "언 땅이 뒤집혔다 — 이번 턴 기온 타격이 2.8배로 치솟습니다.":"The frozen earth heaved open — this turn, warming damage spikes 2.8×.",
  "🩸 생태 티핑 경보":"🩸 Ecosystem Tipping Alert",
  "붕괴 직전 — 이번 턴 생태계 타격이 2.2배로 가속됩니다.":"On the edge of collapse — this turn, ecosystem damage accelerates 2.2×.",
  "🌪️ 복합재난 동시타격":"🌪️ Compound Disaster Strike",
  "방심한 사이 — 이번 턴 모든 악영향이 1.8배로 덮칩니다.":"Caught off guard — this turn, all harmful effects hit 1.8×.",
  "❄️ 라니냐 한숨 돌리기":"❄️ La Niña Breather",
  "잠깐의 냉각 — 이번 턴 기온 타격이 0.6배로 줄어듭니다.":"A brief cooling — this turn, warming damage drops to 0.6×.",
  "📈 그린본드 완판":"📈 Green Bonds Sell Out",
  "녹색 채권이 흥행하며 곳간이 두둑해졌다.":"Green bonds were a hit, fattening the treasury.",
  "🏦 긴급 기후기금 배정":"🏦 Emergency Climate Fund",
  "파산 직전, 국제 기후기금이 수혈됐다.":"On the brink of bankruptcy, an international climate fund stepped in.",
  "💸 탄소세 소송 패소":"💸 Carbon Tax Lawsuit Lost",
  "배상 판결로 곳간이 뜯겼다.":"A damages ruling drained the treasury.",
  "📉 그린버블 차익실현":"📉 Green Bubble Sell-Off",
  "과열된 곳간에 차익실현 매물이 쏟아졌다.":"An overheated treasury was hit by a wave of profit-taking.",
  "📺 기후 다큐 신드롬":"📺 Climate Doc Sensation",
  "온 국민이 다큐에 결집했다.":"The whole nation rallied around a documentary.",
  "🗞️ 그린워싱 스캔들":"🗞️ Greenwashing Scandal",
  "위장 환경정책이 폭로됐다.":"A sham eco-policy was exposed.",
  "🚶 기후 난민 대이동":"🚶 Mass Climate Migration",
  "국경에 몰린 난민에 여론이 들끓는다.":"Refugees massing at the border inflame public opinion.",
  "🫧 여론 거품 붕괴":"🫧 Opinion Bubble Bursts",
  "고공 지지율에 방심한 순간 역풍이 불었다.":"A moment of complacency at sky-high approval triggered a backlash.",
  /* 영구 업적 */
  "🕊️ 파리 협정의 전설":"🕊️ Legend of the Paris Accord",
  "평균 기온 상승을 +1.5°C 이하로 완벽히 방어했습니다.":"Held average warming perfectly under +1.5°C.",
  "🌋 끓어버린 지구":"🌋 Boiled Earth",
  "기온 폭주로 인류가 강제 조기 종료되었습니다.":"Runaway heat forced an early end for humanity.",
  "🍂 침묵의 봄":"🍂 Silent Spring",
  "생태계 건강도 0% 도달로 먹이사슬이 전멸했습니다.":"Ecosystem health hit 0% — the food chain was wiped out.",
  "🤖 프랑켄슈타인 테크":"🤖 Frankenstein Tech",
  "위험한 지구공학 카드를 남발하여 생존했습니다.":"Survived by overusing risky geoengineering cards.",
  "🥶 냉혈한 최고사령관":"🥶 Cold-Blooded Commander",
  "생태 지표를 25% 미만으로 버려둔 채 문명만 보존했습니다.":"Preserved civilization while abandoning the ecosystem below 25%.",
  "💚 완벽주의 통제관":"💚 Perfectionist Overseer",
  "10단계 전부에서 「최선(20점)」 보기만 골라냈습니다.":"Picked only the best (20-pt) option in all 10 stages.",
  "🎲 운명의 도박사":"🎲 Gambler of Fate",
  "확률형 도박 보기를 3번 이상 성공시켰습니다.":"Succeeded on 3 or more chance-based gamble options.",
  /* 통치 페르소나(이름) */
  "인류세를 끝낸 선구자":"Pioneer Who Ended the Anthropocene",
  "벼랑 끝의 승부사":"Brinkmanship Gambler",
  "이상주의 통치자":"The Idealist Ruler",
  "냉혹한 실리주의자":"The Ruthless Pragmatist",
  "타협의 생존가":"The Compromising Survivor",
  "줄타기의 균형감각":"The Tightrope Balancer",
  "표류하는 관리자":"The Drifting Administrator",
  /* 조기 붕괴(돌발 사망) 엔딩 */
  "🪦 배드 엔딩: 텅 빈 세계":"🪦 Bad Ending: The Empty World",
  "생태계 건강 지표가 결국 0%를 뚫고 파산했습니다. 벌과 미생물이 사라져 수정이 불가능해졌고 모든 식생이 고사했습니다. 인류는 지하 벙커에서 영양 배양액으로 연명하는 혹독한 디스토피아를 마주합니다.":"Ecosystem health finally broke through 0% and went bankrupt. Bees and microbes vanished, pollination became impossible, and all vegetation withered. Humanity faces a harsh dystopia, scraping by on nutrient broth in underground bunkers.",
  "🪦 배드 엔딩: 끓어버린 지구":"🪦 Bad Ending: The Boiled Earth",
  "평균 기온 상승이 마지노선인 +3.6°C를 넘어서며 시베리아 영구동토층이 완전히 뒤집혔습니다. 기후 제어 능력을 상실한 지구는 방호복 없이 한 걸음도 걸을 수 없는 거대한 용광로가 되었습니다.":"Average warming crossed the +3.6°C red line and Siberia's permafrost flipped wholesale. Having lost all climate control, Earth became a vast furnace where you can't take a step without a hazmat suit.",
  "평균 기온 상승이 마지노선인 +3.0°C를 넘어서며 시베리아 영구동토층이 완전히 뒤집혔습니다. 기후 제어 능력을 상실한 지구는 방호복 없이 한 걸음도 걸을 수 없는 거대한 용광로가 되었습니다.":"Average warming crossed the +3.0°C red line and Siberia's permafrost flipped wholesale. Having lost all climate control, Earth became a vast furnace where you can't take a step without a hazmat suit.",
  /* 영수증 라벨 */
  "통치 결산 영수증 · GOVERNANCE RECEIPT":"GOVERNANCE RECEIPT",
  "통치 스타일":"Governance Style",
  "최애 목표":"Top Goal",
  "🟢 최선의 결단":"🟢 Best Calls",
  "🟡 절충의 선택":"🟡 Compromises",
  "🟠 아쉬운 균형":"🟠 Shaky Balances",
  "🔴 값비싼 선택":"🔴 Costly Choices",
  "🎲 도박 전적":"🎲 Gamble Record",
  "없음":"None",
  "시그니처 정책":"Signature Policy",
  "🌡️ 기온":"🌡️ Temp.", "🌊 해수면":"🌊 Sea Level", "🌱 생태계":"🌱 Ecosystem",
  "최종 등급":"Final Grade", "지속가능성":"Sustainability", "난이도":"Difficulty",
  "고객님의 지구를 이용해 주셔서":"Thank you for using",
  "감사합니다 🌍":"your Earth 🌍",
  "📸 영수증 저장":"📸 Save Receipt", "← 결과 카드":"← Back to Result",
  "🚨 [돌발 속보]":"🚨 [BREAKING]"
};
